--
--  Active sessions with SQL text
--
--  Tested on: 10g
--


SELECT S.SID, S.SERIAL#, A.SQL_TEXT, S.USERNAME, S.MACHINE
	FROM V$SQLTEXT A,
	V$SESSION S
	WHERE S.SQL_ADDRESS = A.ADDRESS
	AND S.SID IN 
(
	SELECT SID
	FROM V$SESSION
	WHERE LAST_CALL_ET > 5
	AND STATUS = 'ACTIVE'
	AND USERNAME = '&USER'
)
ORDER BY S.SID, A.PIECE;
